baseURL = "https://alexbrogan.com/"
title = "Alex Brogan"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  mainSections = ["essays", "articles", "newsletters", "topics", "testimonials"]
  ShowBreadCrumbs = false
  ShowPostNavLinks = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
