baseURL: "https://alexbrogan.com/"
title: "Alex Brogan"
theme: ["PaperMod"]
contentDir: content
publishDir: public
mainSections:
  - essays
  - articles
  - newsletters
  - topics
  - testimonials
markup:
  goldmark:
    renderer:
      unsafe: true

